---
# SSH Key Setup for Raspberry Pis
# Run this FIRST (before site.yml) to enable passwordless SSH
# Usage: ansible-playbook setup-ssh-keys.yml

- name: Setup SSH key authentication on all Pis
  hosts: pis
  gather_facts: false

  vars:
    # Path to your local SSH public key
    local_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: Add SSH public key to authorized_keys
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        line: "{{ local_ssh_key }}"
        create: true
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: Disable password authentication (optional - recommended after testing)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      become: true
      when: disable_password_auth | default(false)
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
      become: true
