apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany  # NFS supports multiple nodes accessing same volume
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-synology  # Use Synology NAS storage (change to local-path if you prefer local storage)
